name: Build Docker native image and push

on:
  push:
    tags:
        - "*" # build on all tags

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # need this for OIDC
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set tag name to environment
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 17
          distribution: 'graalvm'
          components: 'native-image'
          cache: maven
      - name: Print environment information
        run: |
          java -version
          native-image --version
          gu --version
          mvn --version
          echo ${{ env.TAG_VERSION }}
      - name: Build native Docker image
        run: |
          mvn clean package -Dpackaging=docker-native
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Tag and push Docker image
        run: |
          docker tag httpproxy:latest ${{ secrets.REGISTRY_URL }}/httpproxy:latest
          docker tag httpproxy:latest ${{ secrets.REGISTRY_URL }}/httpproxy:${{ env.TAG_VERSION }}
          docker push ${{ secrets.REGISTRY_URL }}/httpproxy:${{ env.TAG_VERSION }}
          docker push ${{ secrets.REGISTRY_URL }}/httpproxy:latest
